### ISSUE TITLE
Doesn't add runserver_plus command

### ISSUE THREAD

**Issue by Suor** [philippbosch/django-werkzeug-debugger-runserver#2]
``` bash
$ ./manage.py runserver_plus
Unknown command: 'runserver_plus'
Type 'manage.py help' for usage.
```

**Comment by codygman** [comment]
I also have this problem, I'm guessing it isn't compatible with Django 1.8+

**Comment by philippbosch** [comment]
This replaces the regular `runserver` with the debugger-enhanced one. It doesn't add the `runserver_plus` command.
